### PR TITLE
Create chats.ts

### PR DESCRIPTION
**Pull request by JonathanLehner**
It seems that MeteorObservable.subscribe('users').subscribe(); is necessary to activate the Observable and call findOne. Without it, findOne does not return anything and the profile pictures does not show when the app first loads, only after a new chat is started.

### CODE REVIEW

**Comment by darkbasic** [comment]
Can you check if you can still reproduce the issue with the new version of the tutorial? Thanks

**Comment by JonathanLehner** [comment]
I can reproduce it. I used the newest version of the tutorial for it. https://angular-meteor.com/tutorials/whatsapp2/ionic/setup

However, it seems the github repo has some issues. I noticed that there are some wrong plugins on the config file, which led to a crash when I tried git clone. In fact it seems there are quite a lot of differences between the tutorial and the github repo, a few node packages and especially the cordova fb and fcm plugins (and functions in methods.ts). When I clone it, it crashes.

The step-by-step snapshots all fail https://codeload.github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/zip/step4 I would be willing to help fixing it.

**Comment by JonathanLehner** [comment]
I would suggest maybe splitting the tutorial in two parts? or having one simple version? at it might be good to have one stable version available that corresponds to the website

**Comment by darkbasic** [comment]
The tutorial on the Github repo should be stable (or at least works for me without issues) and we will upload it to the website soon. If you encountered a problem please give me more info and I will try to reproduce it, but please don't mix code between the tutorial from the website and the tutorial from Github.

**Comment by JonathanLehner** [comment]
Have you tried to clone the new github repo? I cannot get it to work. I get the error: Meteor settings for accounts-facebook-cordova not configured correctly. And some others. I tried it with the Facebook part (https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/.tortilla/manuals/views/step17.md), but it still does not run without errors.

Is it normal that 
ionic cordova plugin add git+https://github.com/darkbasic/cordova-plugin-facebook4.git --save
does not work? For me it just works without the git, i.e. as
ionic cordova plugin add https://github.com/darkbasic/cordova-plugin-facebook4.git --save

**Comment by JonathanLehner** [comment]
I also get the error 

Runtime Error
Type oid already present

But without much more information.

**Comment by darkbasic** [comment]
> Have you tried to clone the new github repo?
Of course, the new tutorial has been well tested before delivering.

You will need to give me more details about what you are doing to be able to reproduce your issue.

The following is the correct procedure to check out the tutorial from the git repo. You will have to open 2 shells (3 if you want to test it on Android).

Shell 1:
    $ git clone https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp.git
    $ cd Ionic2CLI-Meteor-WhatsApp/
    $ npm install
    $ npm uninstall sharp
    $ meteor npm install sharp
    $ npm run api

[shell1.txt](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/files/1081051/shell1.txt)

Shell 2:
    $ npm run meteor-client:bundle
    $ npm run ionic:serve

[shell2.txt](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/files/1081053/shell2.txt)

Shell 3 (Android testing):
    $ cordova platform add android
    $ cordova run android

[shell3.txt](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/files/1081054/shell3.txt)

Please also post your `npm list -g --depth=0` and your `npm outdated -g`. You will need fresh packages because everything has been rebased.

**Pull request closed without merging**
