### PR TITLE
Update step6.md

### PR DESCRIPTION
**Pull request by OlivierChirouze**
Wrong path for methods.ts.
This looks like a "no big deal" typo but I think it made me loose some time because I misplaced the file and couldn't connect to Meteor (got errors "Exception in delivering result of invoking" in Firefox).
Anyway, thanks for the good work and I hope I'll keep helping, I'm having fun following the tutorial ;-)

### CODE REVIEW

**Comment by DAB0mB** [comment]
@OlivierChirouze We're using an experimental framework to build our tutorials which rebases all the commits, sometimes from root, thus closing all pull requests automatically (without me even knowing). I saw that you opened several of these, so I will go trough them and apply them to the tutorial.

**Comment by OlivierChirouze** [comment]
Thanks, I admit I was surprised by the PR being closed ;)
Keep up the good work!

**Comment by DAB0mB** [comment]
@OlivierChirouze By the way we can give you access to that framework if you're interested this way you can give us your feedback and maybe suggest a new way to accept requests from the community

**Comment by OlivierChirouze** [comment]
I can't garantee that I'll spend much time on it in the near future, but please do and if I can give any valuable feedback, I will.

**Pull request closed without merging**
